packages:
  - packages/*
catalog:
  "@changesets/cli": ^2.24.2
  "@commitlint/cli": ^17.0.0
  "@commitlint/config-conventional": ^17.0.0
  "@forminator/react-wire": ^0.6
  "@microsoft/api-extractor": ^7
  "@testing-library/dom": ^8
  "@testing-library/jest-dom": ^5
  "@testing-library/react": ^13
  "@testing-library/user-event": ^14
  "@types/jest": ^28
  "@types/lodash": ^4
  "@types/node": ^18
  "@types/react": ^18
  "@types/react-dom": ^18
  "@types/testing-library__jest-dom": ^5
  "@vitejs/plugin-react": ^2
  eslint: ^8
  eslint-config-react-app: ^7
  husky: ^8.0.1
  jest: ^28
  jest-environment-jsdom: ^28
  jest-leak-detector: ^29.0.3
  lint-staged: ^13
  lodash: ^4
  prettier: ^2
  react: ^18
  react-dom: ^18
  ts-jest: ^28
  typescript: ^4
  vite: ^3
  vite-plugin-dts: ^1
